name: CD

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  deploy-placeholder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy (placeholder)
        run: echo "Define despliegue (Docker Registry, servidor, etc.)"
